import * as XLSX from 'xlsx'
// 创建一个工作簿和一个工作表
const workbook = XLSX.utils.book_new();
const sheetName = "Employee Data";
const ws = XLSX.utils.json_to_sheet([], {
  header: [
    "Badge",
    "Tec Points",
    "Performance Score",
    "Leader Score",
    "Product Business Mind",
    "Pro Summary Score Sort",
    "Pro Summary Score Nodesc",
    "Comp Age",
    "Comp Age Sort",
    "Per 12",
    "Attitude",
    "Per Sort",
    "Zhiji",
    "Age",
    "Working Age",
    "Working Age Sort",
    "Name",
    "Email",
    "Eid",
    "Schoolname",
    "Education",
    "Main Pro T",
    "Main Pro",
    "Job T",
  ],
});

// 在这里添加你的数据对象
const employeeData = [
  {
    badge: "T00051",
    tec_points: 65.6191,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 62.1715,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈建伟",
    email: "chenjw@myhexin.com",
    eid: "3649",
    schoolname: "浙江工业大学",
    education: "本科",
    main_pro_t: "B2C-11-04-行情服务组",
    main_pro: "636",
    job_t: "架构师",
  },
  {
    badge: "T23074",
    tec_points: 65.1223,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.8734,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "郑祥作",
    email: "zhengxiangzuo@myhexin.com",
    eid: "31171",
    schoolname: "中国科学院研究生院",
    education: "硕士研究生",
    main_pro_t: "B2C-11-04-行情服务组",
    main_pro: "636",
    job_t: "技术专家",
  },
  {
    badge: "T15245",
    tec_points: {
      value: 65.0863,
      info: "23年落地公司架构DTS落地：\n任务数259个，业务方22个（包括各个业务方海外数据同步，ifind数据同步）\n日增数据量：1.5T左右\n\n1、数据库连接组件：mybatis及mybatis-plus层异常告警及指标监控 druid连接池指标数据统计。 2、sharding proxy的中间件技术公关。为了解决未来分库分表自动扩容的问题。对标阿里的TDDL。\n",
      path: "Public/data/pdbasescoreIcon/611cf45b98bcf.png",
      haveBaseScore: true,
    },
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.8518,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "林金波",
    email: "linjinbo@myhexin.com",
    eid: "21751",
    schoolname: "浙江大学",
    education: "本科",
    main_pro_t: "B2C-M07-场外基金2B",
    main_pro: "468",
    job_t: "Java开发工程师",
  },
  {
    badge: "T03544",
    tec_points: 65.0616,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.837,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "宋策",
    email: "songce@myhexin.com",
    eid: "6495",
    schoolname: "浙江工业大学",
    education: "本科",
    main_pro_t: "B2C-M01-收费软件",
    main_pro: "340",
    job_t: "前端开发工程师",
  },
  {
    badge: "T11893",
    tec_points: 64.3135,
    performance_score: 60.8754,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.6507,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "单腾晖",
    email: "shantenghui@myhexin.com",
    eid: "17810",
    schoolname: "浙江科技学院",
    education: "本科",
    main_pro_t: "B2C-03-手 机",
    main_pro: "318",
    job_t: "前端开发工程师",
  },
  {
    badge: "T15134",
    tec_points: 64.2502,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.3501,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "徐晶晶",
    email: "xujingjing@myhexin.com",
    eid: "21631",
    schoolname: "浙江大学",
    education: "本科",
    main_pro_t: "B2C-03-手 机",
    main_pro: "318",
    job_t: "iOS开发工程师",
  },
  {
    badge: "T16263",
    tec_points: {
      value: 64.1396,
      info: "CR Hipilot Agent 在基金和其他业务团队落地\n",
      path: "Public/data/pdbasescoreIcon/611cf45b98bcf.png",
      haveBaseScore: true,
    },
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.2838,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈炜",
    email: "chenwei2@myhexin.com",
    eid: "23013",
    schoolname: "浙江工业大学",
    education: "本科",
    main_pro_t: "B2C-11-技术架构升级",
    main_pro: "522",
    job_t: "Java开发工程师",
  },
  {
    badge: "T15415",
    tec_points: 64.0957,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.2574,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "李博深",
    email: "liboshen@myhexin.com",
    eid: "21936",
    schoolname: "合肥工业大学",
    education: "本科",
    main_pro_t: "B2C-M02-基金",
    main_pro: "341",
    job_t: "前端开发工程师",
  },
  {
    badge: "T15051",
    tec_points: 63.8581,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.1149,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "唐玉杰",
    email: "tangyujie@myhexin.com",
    eid: "21497",
    schoolname: "浙江工业大学",
    education: "硕士研究生",
    main_pro_t: "B2C-M03-开 户",
    main_pro: "342",
    job_t: "Java开发工程师",
  },
  {
    badge: "T08995",
    tec_points: 63.7732,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.0639,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "郑中文",
    email: "zhengzhongwen@myhexin.com",
    eid: "14280",
    schoolname: "浙江工业大学",
    education: "本科",
    main_pro_t: "B2C-03-手 机",
    main_pro: "318",
    job_t: "iOS开发工程师",
  },
  {
    badge: "T00592",
    tec_points: 63.6332,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.9799,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "彭永建",
    email: "pengyongjian@myhexin.com",
    eid: "3605",
    schoolname: "浙江中医药大学",
    education: "本科",
    main_pro_t: "B2C-11-04-行情服务组",
    main_pro: "636",
    job_t: "C++开发工程师",
  },
  {
    badge: "T13959",
    tec_points: 63.5494,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.9296,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "柳岩",
    email: "liuyan3@myhexin.com",
    eid: "20165",
    schoolname: "浙江工业大学",
    education: "本科",
    main_pro_t: "B2C-10-B2C期货",
    main_pro: "271",
    job_t: "iOS开发工程师",
  },
  {
    badge: "T18509",
    tec_points: 63.4853,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.8912,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "崔啸宇",
    email: "cuixiaoyu@myhexin.com",
    eid: "25042",
    schoolname: "长安大学",
    education: "本科",
    main_pro_t: "B2C-01-08-账户分析",
    main_pro: "339",
    job_t: "Java开发工程师",
  },
  {
    badge: "T16909",
    tec_points: 63.4414,
    performance_score: 61.8833,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.4298,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "吴江涛",
    email: "wujiangtao2@myhexin.com",
    eid: "23626",
    schoolname: "上海交通大学",
    education: "硕士研究生",
    main_pro_t: "B2C-04-01-PC统一版",
    main_pro: "476",
    job_t: "C++开发工程师",
  },
  {
    badge: "T09901",
    tec_points: 63.3823,
    performance_score: 60.0034,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.8304,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "郑慧霖",
    email: "zhenghuilin@myhexin.com",
    eid: "15479",
    schoolname: "杭州师范大学",
    education: "本科",
    main_pro_t: "B2C-M01-收费软件",
    main_pro: "340",
    job_t: "前端开发工程师",
  },
  {
    badge: "T00973",
    tec_points: 63.3809,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.8285,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈嗣雄",
    email: "chensixiong@myhexin.com",
    eid: "4365",
    schoolname: "杭州电子科技大学",
    education: "本科",
    main_pro_t: "B2C-ZT-产品运营中台",
    main_pro: "441",
    job_t: "Java开发工程师",
  },
  {
    badge: "T00342",
    tec_points: 63.3247,
    performance_score: 63.5455,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.8585,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈力夫",
    email: "chenlifu@myhexin.com",
    eid: "4877",
    schoolname: "杭州电子科技大学",
    education: "本科",
    main_pro_t: "B2C-01-08-账户分析",
    main_pro: "339",
    job_t: "Java开发工程师",
  },
  {
    badge: "T19283",
    tec_points: 63.3104,
    performance_score: 60.8863,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 61.0521,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "王彬彬",
    email: "wangbinbin@myhexin.com",
    eid: "26800",
    schoolname: "浙江理工大学",
    education: "本科",
    main_pro_t: "B2C-09-资 讯",
    main_pro: "321",
    job_t: "前端开发工程师",
  },
  {
    badge: "T12563",
    tec_points: {
      value: 63.3101,
      info: "b2c java CICD 的插件负责人。\nsonar 维护，源代码修改，破解收费版本，支持多线程。提高sonar的并发量。\nmango的指标负责人。",
      path: "Public/data/pdbasescoreIcon/611cf45b98bcf.png",
      haveBaseScore: true,
    },
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.7861,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "韩进祥",
    email: "hanjinxiang@myhexin.com",
    eid: "18571",
    schoolname: "西安工业大学",
    education: "本科",
    main_pro_t: "B2C-01-03-F 10",
    main_pro: "322",
    job_t: "Java开发工程师",
  },
  {
    badge: "T16848",
    tec_points: 63.2211,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.7327,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "周云峰",
    email: "zhouyunfeng@myhexin.com",
    eid: "23720",
    schoolname: "南京邮电大学",
    education: "本科",
    main_pro_t: "B2C-M06-场内基金ETF",
    main_pro: "535",
    job_t: "iOS开发工程师",
  },
  {
    badge: "T21882",
    tec_points: 63.0593,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.6356,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "刘捷",
    email: "liujie6@myhexin.com",
    eid: "29734",
    schoolname: "浙江工业大学",
    education: "硕士研究生",
    main_pro_t: "B2C-M02-01-核心功能建设",
    main_pro: "463",
    job_t: "前端开发工程师",
  },
  {
    badge: "T00236",
    tec_points: {
      value: 63.0448,
      info: "1、牵头搭建了自动化测试平台。\n2.参考OpenSergo和北极星设计了流量防护，统一数据面方案。\n\nB2C web后端架构师，今年牵头引入了HexinBoot框架：\n\nhttp://172.20.200.191:8003/pages/viewpage.action?pageId=672629204\n\n今年还接入脚手架，提高整个B2C后端100多开发的工作效率\n\nhttp://172.20.200.191:8003/pages/viewpage.action?pageId=695599578\n",
      path: "Public/data/pdbasescoreIcon/611cf45b98bcf.png",
      haveBaseScore: true,
    },
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.6269,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "吴方国",
    email: "wufangguo@myhexin.com",
    eid: "2773",
    schoolname: "浙江工业大学",
    education: "硕士研究生",
    main_pro_t: "B2C-11-技术架构升级",
    main_pro: "522",
    job_t: "Java开发工程师",
  },
  {
    badge: "T03833",
    tec_points: 63.0179,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.6107,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "何建乔",
    email: "hejianqiao@myhexin.com",
    eid: "6735",
    schoolname: "浙江工业大学",
    education: "本科",
    main_pro_t: "B2C-01-10-投 顾",
    main_pro: "356",
    job_t: "web后端开发工程师",
  },
  {
    badge: "T15086",
    tec_points: 62.8961,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.5377,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "赵攀",
    email: "zhaopan@myhexin.com",
    eid: "21542",
    schoolname: "武汉理工大学",
    education: "本科",
    main_pro_t: "B2C-01-07-手 机自运营交易",
    main_pro: "338",
    job_t: "iOS开发工程师",
  },
  {
    badge: "T15244",
    tec_points: 62.886,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.5316,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "徐庆明",
    email: "xuqingming@myhexin.com",
    eid: "21796",
    schoolname: "杭州电子科技大学",
    education: "本科",
    main_pro_t: "B2C-10-B2C期货",
    main_pro: "271",
    job_t: "iOS开发工程师",
  },
  {
    badge: "T19121",
    tec_points: 62.7733,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.464,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "焦龙飞",
    email: "jiaolongfei@myhexin.com",
    eid: "26513",
    schoolname: "哈尔滨理工大学",
    education: "本科",
    main_pro_t: "B2C-04-02-PC远航版",
    main_pro: "477",
    job_t: "C++开发工程师",
  },
  {
    badge: "T05902",
    tec_points: {
      value: 62.7502,
      info: "http指标维护。\n整个公司maven 仓库的负责人，做了仓库故障分钟切换方案。保障所有开发在编译、打包、发布过程的可靠性。",
      path: "Public/data/pdbasescoreIcon/611cf45b98bcf.png",
      haveBaseScore: true,
    },
    performance_score: 60.0071,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.4523,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈聪颖",
    email: "chencongying@myhexin.com",
    eid: "11267",
    schoolname: "浙江工业大学",
    education: "本科",
    main_pro_t: "B2C-03-手 机",
    main_pro: "318",
    job_t: "Java开发工程师",
  },
  {
    badge: "T21961",
    tec_points: 62.7465,
    performance_score: 60.187,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.504,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈禄海",
    email: "chenluhai@myhexin.com",
    eid: "29765",
    schoolname: "中国农业大学",
    education: "硕士研究生",
    main_pro_t: "B2C-04-02-PC远航版",
    main_pro: "477",
    job_t: "C#开发工程师",
  },
  {
    badge: "T00222",
    tec_points: {
      value: 62.6899,
      info: "统一公司的网关（支持了安全证书下发和eip能力），实现网关标准化，解决了流量网关多活问题。\n\nhexinboot redis 指标负责。\n脚手架IDE插件开发。内网数据mock平台开发。",
      path: "Public/data/pdbasescoreIcon/611cf45b98bcf.png",
      haveBaseScore: true,
    },
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.4139,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "鲁刚",
    email: "lugang@myhexin.com",
    eid: "3615",
    schoolname: "浙江商业职业技术学院",
    education: "大专",
    main_pro_t: "B2C-M01-收费软件",
    main_pro: "340",
    job_t: "Java开发工程师",
  },
  {
    badge: "T03310",
    tec_points: 62.619,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.3714,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "董虎飞",
    email: "donghufei@myhexin.com",
    eid: "4467",
    schoolname: "河南工业大学",
    education: "本科",
    main_pro_t: "B2C-10-B2C期货",
    main_pro: "271",
    job_t: "iOS开发工程师",
  },
  {
    badge: "T06418",
    tec_points: 62.6143,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.3686,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "王卓",
    email: "wangzhuo@myhexin.com",
    eid: "11962",
    schoolname: "哈尔滨工业大学",
    education: "硕士研究生",
    main_pro_t: "B2C-03-手 机",
    main_pro: "318",
    job_t: "Android开发工程师",
  },
  {
    badge: "T20252",
    tec_points: 62.5665,
    performance_score: 74.8155,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 64.7846,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "姜东宇",
    email: "jiangdongyu@myhexin.com",
    eid: "27820",
    schoolname: "电信科学技术研究院",
    education: "硕士研究生",
    main_pro_t: "B2C-01-09-社区",
    main_pro: "355",
    job_t: "Java开发工程师",
  },
  {
    badge: "T20683",
    tec_points: 62.5419,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.3251,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "林德相",
    email: "lindexiang@myhexin.com",
    eid: "28562",
    schoolname: "同济大学",
    education: "硕士研究生",
    main_pro_t: "B2C-01-04-港美股与东南亚项目",
    main_pro: "323",
    job_t: "Java开发工程师",
  },
  {
    badge: "T22359",
    tec_points: 62.526,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.3156,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "刘帅",
    email: "liushuai6@myhexin.com",
    eid: "30255",
    schoolname: "中国科学技术大学",
    education: "硕士研究生",
    main_pro_t: "B2C-01-03-F 10",
    main_pro: "322",
    job_t: "前端开发工程师",
  },
  {
    badge: "T05168",
    tec_points: 62.4945,
    performance_score: 60.0418,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.3092,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "李浩锐",
    email: "lihaorui@myhexin.com",
    eid: "10218",
    schoolname: "厦门大学",
    education: "本科",
    main_pro_t: "B2C-11-01-AppStore插件化",
    main_pro: "624",
    job_t: "Java开发工程师",
  },
  {
    badge: "T14810",
    tec_points: 62.487,
    performance_score: 60.1631,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.3411,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "穆泓宋",
    email: "muhongsong@myhexin.com",
    eid: "19929",
    schoolname: "西北农林科技大学",
    education: "本科",
    main_pro_t: "B2C-M01-收费软件",
    main_pro: "340",
    job_t: "前端开发工程师",
  },
  {
    badge: "T23138",
    tec_points: 62.4629,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.2777,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "郭俊川",
    email: "guojunchuan@myhexin.com",
    eid: "31207",
    schoolname: "电子科技大学",
    education: "硕士研究生",
    main_pro_t: "B2C-04-02-PC远航版",
    main_pro: "477",
    job_t: "C#开发工程师",
  },
  {
    badge: "T15259",
    tec_points: 62.4165,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.2499,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "刘尚书",
    email: "liushangshu@myhexin.com",
    eid: "21755",
    schoolname: "南京邮电大学",
    education: "本科",
    main_pro_t: "B2C-M02-01-核心功能建设",
    main_pro: "463",
    job_t: "Android开发工程师",
  },
  {
    badge: "T08507",
    tec_points: 62.4056,
    performance_score: 60.2565,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.3203,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "王明",
    email: "wangming@myhexin.com",
    eid: "13542",
    schoolname: "湖州师范学院",
    education: "本科",
    main_pro_t: "B2C-01-09-社区",
    main_pro: "355",
    job_t: "Java开发工程师",
  },
  {
    badge: "T04728",
    tec_points: 62.4031,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.2419,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈舜熙",
    email: "chenshunxi@myhexin.com",
    eid: "8983",
    schoolname: "福建工程学院",
    education: "本科",
    main_pro_t: "B2C-M02-01-核心功能建设",
    main_pro: "463",
    job_t: "Java开发工程师",
  },
  {
    badge: "T18870",
    tec_points: 62.3901,
    performance_score: 60.073,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.256,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "刘家清",
    email: "liujiaqing@myhexin.com",
    eid: "26239",
    schoolname: "江西师范大学",
    education: "本科",
    main_pro_t: "B2C-M05-理财产品销售",
    main_pro: "622",
    job_t: "Java开发工程师",
  },
  {
    badge: "T02972",
    tec_points: 62.3583,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.215,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "周鹏",
    email: "zhoupeng@myhexin.com",
    eid: "3597",
    schoolname: "浙江工业大学",
    education: "本科",
    main_pro_t: "B2C-11-04-行情服务组",
    main_pro: "636",
    job_t: "C++开发工程师",
  },
  {
    badge: "T14582",
    tec_points: {
      value: 62.3342,
      info: "23年：业务链路最终平台，解决了投顾下单全链路5分钟定位问题，并且推广到小财神。\n\n负责hexin-boot的版本维护。\nkafka性能指标，分布式锁。\nDDD和MVC脚手架。",
      path: "Public/data/pdbasescoreIcon/611cf45b98bcf.png",
      haveBaseScore: true,
    },
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.2005,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "林子立",
    email: "linzili@myhexin.com",
    eid: "21108",
    schoolname: "西南大学",
    education: "本科",
    main_pro_t: "B2C-01-10-投 顾",
    main_pro: "356",
    job_t: "Java开发工程师",
  },
  {
    badge: "T19234",
    tec_points: 62.3274,
    performance_score: 60.0675,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.2167,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "谭心睿",
    email: "tanxinrui@myhexin.com",
    eid: "26692",
    schoolname: "中国地质大学（武汉）",
    education: "本科",
    main_pro_t: "B2C-01-09-社区",
    main_pro: "355",
    job_t: "前端开发工程师",
  },
  {
    badge: "T00936",
    tec_points: 62.3208,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.1925,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "潘永智",
    email: "panyongzhi@myhexin.com",
    eid: "4311",
    schoolname: "杭州电子科技大学",
    education: "本科",
    main_pro_t: "B2C-11-04-行情服务组",
    main_pro: "636",
    job_t: "C++开发工程师",
  },
  {
    badge: "T08294",
    tec_points: 62.2786,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.1672,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "王流刚",
    email: "wangliugang@myhexin.com",
    eid: "13543",
    schoolname: "浙江科技学院",
    education: "本科",
    main_pro_t: "B2C-01-09-社区",
    main_pro: "355",
    job_t: "Java开发工程师",
  },
  {
    badge: "T00611",
    tec_points: 62.2733,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.164,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "占志雄",
    email: "zhanzhixiong@myhexin.com",
    eid: "2813",
    schoolname: "华东交通大学",
    education: "本科",
    main_pro_t: "B2C-M01-01-电 销&客 服",
    main_pro: "357",
    job_t: "Java开发工程师",
  },
  {
    badge: "T00716",
    tec_points: 62.2494,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.1496,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "张闪",
    email: "zhangshan2@myhexin.com",
    eid: "4347",
    schoolname: "河南大学",
    education: "本科",
    main_pro_t: "B2C-10-B2C期货",
    main_pro: "271",
    job_t: "Android开发工程师",
  },
  {
    badge: "T04754",
    tec_points: 62.2484,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.149,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "黄奇超",
    email: "huangqichao@myhexin.com",
    eid: "8975",
    schoolname: "西北农林科技大学",
    education: "本科",
    main_pro_t: "B2C-03-手 机",
    main_pro: "318",
    job_t: "Android开发工程师",
  },
  {
    badge: "T12958",
    tec_points: 62.2462,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.1477,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "李鲁宾",
    email: "lilubin@myhexin.com",
    eid: "19065",
    schoolname: "杭州电子科技大学",
    education: "本科",
    main_pro_t: "B2C-10-B2C期货",
    main_pro: "271",
    job_t: "iOS开发工程师",
  },
  {
    badge: "T16265",
    tec_points: 62.2421,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.1453,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "张新浙",
    email: "zhangxinzhe@myhexin.com",
    eid: "22783",
    schoolname: "杭州电子科技大学",
    education: "本科",
    main_pro_t: "B2C-M03-开 户",
    main_pro: "342",
    job_t: "Java开发工程师",
  },
  {
    badge: "T00252",
    tec_points: 62.2283,
    performance_score: 61.3978,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.5563,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "全卢灿",
    email: "quanlucan@myhexin.com",
    eid: "4887",
    schoolname: "温州大学",
    education: "本科",
    main_pro_t: "B2C-01-08-账户分析",
    main_pro: "339",
    job_t: "前端开发工程师",
  },
  {
    badge: "T00709",
    tec_points: 62.2032,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.1219,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "熊厚淼",
    email: "xionghoumiao@myhexin.com",
    eid: "4573",
    schoolname: "杭州师范大学",
    education: "本科",
    main_pro_t: "B2C-07-投资课堂",
    main_pro: "437",
    job_t: "Android开发工程师",
  },
  {
    badge: "T13999",
    tec_points: 62.2006,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.1204,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "冯涛",
    email: "fengtao2@myhexin.com",
    eid: "20348",
    schoolname: "合肥工业大学",
    education: "本科",
    main_pro_t: "B2C-01-04-港美股与东南亚项目",
    main_pro: "323",
    job_t: "前端开发工程师",
  },
  {
    badge: "T12609",
    tec_points: 62.1978,
    performance_score: 60.0119,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.1223,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "吴迪",
    email: "wudi3@myhexin.com",
    eid: "18663",
    schoolname: "南通大学",
    education: "本科",
    main_pro_t: "B2C-01-08-账户分析",
    main_pro: "339",
    job_t: "Java开发工程师",
  },
  {
    badge: "T16187",
    tec_points: 62.1964,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.1178,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "魏浩洋",
    email: "weihaoyang@myhexin.com",
    eid: "22370",
    schoolname: "华中科技大学",
    education: "硕士研究生",
    main_pro_t: "B2C-11-04-行情服务组",
    main_pro: "636",
    job_t: "C++开发工程师",
  },
  {
    badge: "T16770",
    tec_points: 62.184,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.1104,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "曾雍皓",
    email: "zengyonghao@myhexin.com",
    eid: "23755",
    schoolname: "西南民族大学",
    education: "本科",
    main_pro_t: "B2C-10-B2C期货",
    main_pro: "271",
    job_t: "Android开发工程师",
  },
  {
    badge: "T01476",
    tec_points: 62.1275,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.0765,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "李轲",
    email: "like2@myhexin.com",
    eid: "4897",
    schoolname: "河南工业大学",
    education: "本科",
    main_pro_t: "B2C-04-03-MAC版：国内&国外",
    main_pro: "478",
    job_t: "Mac开发工程师",
  },
  {
    badge: "T17660",
    tec_points: {
      value: 62.0879,
      info: "1、跟GMS共建，自研websocket。解决海外PC web 行情。目前国内A股的web行情（比如F10，虚拟人等）\n2、owner 自动化测试平，今年完成接口自动化引擎（http、dubbo），提供测试效率，后续支持行情（tcp等）",
      path: "Public/data/pdbasescoreIcon/611cf45b98bcf.png",
      haveBaseScore: true,
    },
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.0527,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "董轩梁",
    email: "dongxuanliang@myhexin.com",
    eid: "24767",
    schoolname: "浙江工业大学",
    education: "本科",
    main_pro_t: "B2C-11-技术架构升级",
    main_pro: "522",
    job_t: "Java开发工程师",
  },
  {
    badge: "T13581",
    tec_points: 62.0836,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.0502,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "雷项阳",
    email: "leixiangyang@myhexin.com",
    eid: "19782",
    schoolname: "杭州电子科技大学",
    education: "本科",
    main_pro_t: "B2C-09-资 讯",
    main_pro: "321",
    job_t: "Java开发工程师",
  },
  {
    badge: "T11423",
    tec_points: 62.0727,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.0436,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈胜杰",
    email: "chenshengjie@myhexin.com",
    eid: "17299",
    schoolname: "文华学院",
    education: "本科",
    main_pro_t: "B2C-01-08-账户分析",
    main_pro: "339",
    job_t: "前端开发工程师",
  },
  {
    badge: "T06138",
    tec_points: 62.0207,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.0124,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "张飞",
    email: "zhangfei2@myhexin.com",
    eid: "11592",
    schoolname: "浙江工业大学",
    education: "硕士研究生",
    main_pro_t: "B2C-M02-01-核心功能建设",
    main_pro: "463",
    job_t: "Java开发工程师",
  },
  {
    badge: "T24347",
    tec_points: 62.0021,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈恒(试用)",
    email: "chenheng@myhexin.com",
    eid: "32038",
    schoolname: "厦门大学",
    education: "本科",
    main_pro_t: "B2C-04-01-PC统一版",
    main_pro: "476",
    job_t: "C++开发工程师",
    isShiyong: true,
  },
  {
    badge: "T17237",
    tec_points: 61.9812,
    performance_score: 60.8198,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.2347,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "阮翔",
    email: "ruanxiang@myhexin.com",
    eid: "23909",
    schoolname: "杭州师范大学",
    education: "本科",
    main_pro_t: "B2C-03-手 机",
    main_pro: "318",
    job_t: "前端开发工程师",
  },
  {
    badge: "T17194",
    tec_points: 61.9687,
    performance_score: 61.3475,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.3855,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈孟宋",
    email: "chenmengsong@myhexin.com",
    eid: "24195",
    schoolname: "北京航空航天大学",
    education: "本科",
    main_pro_t: "B2C-01-09-社区",
    main_pro: "355",
    job_t: "Java开发工程师",
  },
  {
    badge: "T10613",
    tec_points: 61.9611,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.9767,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "胡晨龙",
    email: "huchenlong@myhexin.com",
    eid: "16411",
    schoolname: "宜春学院",
    education: "本科",
    main_pro_t: "B2C-01-04-港美股与东南亚项目",
    main_pro: "323",
    job_t: "C++开发工程师",
  },
  {
    badge: "T16515",
    tec_points: 61.947,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.9682,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "汪超伟",
    email: "wangchaowei@myhexin.com",
    eid: "23280",
    schoolname: "苏州大学",
    education: "本科",
    main_pro_t: "B2C-01-06-P C自运营交易",
    main_pro: "337",
    job_t: "C++开发工程师",
  },
  {
    badge: "T06085",
    tec_points: 61.9332,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.9599,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "韩坚",
    email: "hanjian@myhexin.com",
    eid: "11454",
    schoolname: "浙江大学",
    education: "硕士研究生",
    main_pro_t: "B2C-03-手 机",
    main_pro: "318",
    job_t: "iOS开发工程师",
  },
  {
    badge: "T15046",
    tec_points: 61.898,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.9388,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陶浩洲",
    email: "taohaozhou@myhexin.com",
    eid: "21296",
    schoolname: "中国矿业大学（北京）",
    education: "硕士研究生",
    main_pro_t: "B2C-M01-收费软件",
    main_pro: "340",
    job_t: "Java开发工程师",
  },
  {
    badge: "T01676",
    tec_points: 61.8586,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.9152,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "林吕贝",
    email: "linlvbei@myhexin.com",
    eid: "3645",
    schoolname: "浙江农林大学暨阳学院",
    education: "本科",
    main_pro_t: "B2C-01-03-F 10",
    main_pro: "322",
    job_t: "前端开发工程师",
  },
  {
    badge: "T17949",
    tec_points: 61.8562,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.9137,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "温哲",
    email: "wenzhe@myhexin.com",
    eid: "25005",
    schoolname: "西南大学",
    education: "本科",
    main_pro_t: "B2C-10-B2C期货",
    main_pro: "271",
    job_t: "iOS开发工程师",
  },
  {
    badge: "T19241",
    tec_points: 61.8314,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.8988,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "毛炳侥",
    email: "maobingyao@myhexin.com",
    eid: "26351",
    schoolname: "浙江理工大学",
    education: "本科",
    main_pro_t: "B2C-09-资 讯",
    main_pro: "321",
    job_t: "前端开发工程师",
  },
  {
    badge: "T20374",
    tec_points: 61.8301,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.8981,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈立波",
    email: "chenlibo3@myhexin.com",
    eid: "28117",
    schoolname: "台州学院",
    education: "本科",
    main_pro_t: "B2C-03-手 机",
    main_pro: "318",
    job_t: "Android开发工程师",
  },
  {
    badge: "T03551",
    tec_points: 61.8037,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.8822,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "魏军峰",
    email: "weijunfeng@myhexin.com",
    eid: "5403",
    schoolname: "安徽工业大学",
    education: "本科",
    main_pro_t: "B2C-10-B2C期货",
    main_pro: "271",
    job_t: "Android开发工程师",
  },
  {
    badge: "T15076",
    tec_points: 61.7895,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.8737,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "史进",
    email: "shijin@myhexin.com",
    eid: "21635",
    schoolname: "辽宁科技大学",
    education: "本科",
    main_pro_t: "B2C-01-07-手 机自运营交易",
    main_pro: "338",
    job_t: "iOS开发工程师",
  },
  {
    badge: "T14942",
    tec_points: 61.7836,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.8702,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "张磊",
    email: "zhanglei4@myhexin.com",
    eid: "20175",
    schoolname: "哈尔滨工业大学（威海）",
    education: "本科",
    main_pro_t: "B2C-03-手 机",
    main_pro: "318",
    job_t: "Android开发工程师",
  },
  {
    badge: "T10582",
    tec_points: 61.7806,
    performance_score: 63.1734,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 60.8204,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "朱少威",
    email: "zhushaowei@myhexin.com",
    eid: "16097",
    schoolname: "河南科技大学",
    education: "本科",
    main_pro_t: "B2C-01-07-手 机自运营交易",
    main_pro: "338",
    job_t: "Android开发工程师",
  },
  {
    badge: "T07862",
    tec_points: 61.7371,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.8423,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "鲁铸群",
    email: "luzhuqun@myhexin.com",
    eid: "13042",
    schoolname: "河海大学",
    education: "本科",
    main_pro_t: "B2C-09-资 讯",
    main_pro: "321",
    job_t: "Java开发工程师",
  },
  {
    badge: "T15365",
    tec_points: 61.7222,
    performance_score: 60.0473,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.8475,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "倪雪冰",
    email: "nixuebing@myhexin.com",
    eid: "21905",
    schoolname: "西安电子科技大学",
    education: "本科",
    main_pro_t: "B2C-09-资 讯",
    main_pro: "321",
    job_t: "Java开发工程师",
  },
  {
    badge: "T03938",
    tec_points: 61.7049,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.8229,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "杜卫斌",
    email: "duweibin@myhexin.com",
    eid: "6949",
    schoolname: "平顶山学院",
    education: "本科",
    main_pro_t: "B2C-ZT-产品运营中台",
    main_pro: "441",
    job_t: "Java开发工程师",
  },
  {
    badge: "T01667",
    tec_points: 61.689,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.8134,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "许潇",
    email: "xuxiao@myhexin.com",
    eid: "3655",
    schoolname: "西安工业大学",
    education: "本科",
    main_pro_t: "B2C-10-B2C期货",
    main_pro: "271",
    job_t: "C++开发工程师",
  },
  {
    badge: "T19759",
    tec_points: 61.6841,
    performance_score: 60.0049,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.8119,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "李献涛",
    email: "lixiantao@myhexin.com",
    eid: "27356",
    schoolname: "西安电子科技大学",
    education: "本科",
    main_pro_t: "B2C-M02-01-核心功能建设",
    main_pro: "463",
    job_t: "Java开发工程师",
  },
  {
    badge: "T20373",
    tec_points: 61.6704,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.8022,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "田浩",
    email: "tianhao2@myhexin.com",
    eid: "28112",
    schoolname: "东南大学",
    education: "硕士研究生",
    main_pro_t: "B2C-11-01-AppStore插件化",
    main_pro: "624",
    job_t: "Java开发工程师",
  },
  {
    badge: "T07274",
    tec_points: 61.6623,
    performance_score: 90,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 68.7974,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "曾超",
    email: "zengchao@myhexin.com",
    eid: "12207",
    schoolname: "湖北大学知行学院",
    education: "本科",
    main_pro_t: "B2C-M03-开 户",
    main_pro: "342",
    job_t: "Android开发工程师",
  },
  {
    badge: "T17037",
    tec_points: 61.613,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.7678,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "蒋良剑",
    email: "jiangliangjian@myhexin.com",
    eid: "23963",
    schoolname: "浙江工业大学",
    education: "本科",
    main_pro_t: "B2C-M02-02-用户运营",
    main_pro: "466",
    job_t: "Java开发工程师",
  },
  {
    badge: "T19100",
    tec_points: 61.5944,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.7566,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "龚柯",
    email: "gongke@myhexin.com",
    eid: "26428",
    schoolname: "浙江理工大学",
    education: "本科",
    main_pro_t: "B2C-01-03-F 10",
    main_pro: "322",
    job_t: "前端开发工程师",
  },
  {
    badge: "T15553",
    tec_points: 61.5633,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.738,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "孟璐",
    email: "menglu@myhexin.com",
    eid: "21978",
    schoolname: "大连理工大学",
    education: "本科",
    main_pro_t: "B2C-11-04-行情服务组",
    main_pro: "636",
    job_t: "C++开发工程师",
  },
  {
    badge: "T18617",
    tec_points: 61.5601,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.7361,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "陈伟",
    email: "chenwei4@myhexin.com",
    eid: "25965",
    schoolname: "浙江工业大学",
    education: "本科",
    main_pro_t: "B2C-08-视频内容",
    main_pro: "442",
    job_t: "Android开发工程师",
  },
  {
    badge: "T23054",
    tec_points: 61.5191,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.7115,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "林子焱",
    email: "linziyan@myhexin.com",
    eid: "30685",
    schoolname: "加利福尼亚大学尔湾分校",
    education: "硕士研究生",
    main_pro_t: "AI6-MP-DV-数据可视化中台",
    main_pro: "170",
    job_t: "前端开发工程师",
  },
  {
    badge: "T13403",
    tec_points: 61.4939,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.6963,
    pro_summary_score_nodesc: "B-",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "辛卫涛",
    email: "xinweitao@myhexin.com",
    eid: "19608",
    schoolname: "浙江工业大学",
    education: "硕士研究生",
    main_pro_t: "B2C-01-04-港美股与东南亚项目",
    main_pro: "323",
    job_t: "Java开发工程师",
  },
  {
    badge: "T24338",
    tec_points: 61.4916,
    performance_score: 60,
    leader_score: 60,
    product_business_mind_score: 60,
    pro_summary_score_sort: 59.695,
    pro_summary_score_nodesc: "C+",
    comp_age: "暂无",
    comp_age_sort: "暂无",
    per_12: "暂无",
    attitude: "暂无",
    per_sort: "暂无",
    zhiji: "暂无",
    age: "暂无",
    working_age: "暂无",
    working_age_sort: "暂无",
    name: "弓少旭",
    email: "gongshaoxu@myhexin.com",
    eid: "32069",
    schoolname: "中国地质大学(武汉)",
    education: "本科",
    main_pro_t: "B2C-09-资 讯",
    main_pro: "321",
    job_t: "前端开发工程师",
    order_rank: 91,
  },
];

// 将数据添加到工作表中
XLSX.utils.sheet_add_json(ws, employeeData, { skipHeader: true, origin: -1 });

// 将工作表添加到工作簿中
XLSX.utils.book_append_sheet(workbook, ws, sheetName);

// 将工作簿保存为 Excel 文件
XLSX.writeFile(workbook, "employee_data.xlsx");

console.log("Excel file 'employee_data.xlsx' created successfully.");
